osx_image: xcode11.3
language: swift
install:
  - gem install slather
script:
  - xcodebuild -workspace bowling.xcworkspace -scheme bowling -sdk iphonesimulator -destination 'name=iPhone 11 Pro Max' test | xcpretty
  - slather
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
  - bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml
  
after_success:
